### ISSUE TITLE
unable to load simple.html

### ISSUE THREAD

**Issue by andrewlook** [distillpub/post--feature-visualization#20]
From the readme: "Visit localhost:8080/index.html for a compilation of all components, localhost:8080/simple.html for an isolated example."

However, `npm run dev` followed by opening http://localhost:8080/simple.html results in: `Cannot GET /simple.html`

I'd find it pretty helpful to see how the developers iterated on the components - I'm assuming that something like `simple.ejs` is in the git history somewhere.

If it's helpful, I'd be happy to spin up a PR either reviving simple.ejs, or updating the README to reflect the current state.

**Comment by ludwigschubert** [comment]
Yeah, we no longer have support for that. It would be handy, though! IIRC the problem was we couldn't dynamically import a given component, and deemed it too much work to always change the imports manually—I still would really like to have this, but if your entire article is slow to load and refresh you have a more fundamental performance problem. If you'd create a PR making something like that work, you may prefer to directly do so on [distillpub/template](https://github.com/distillpub/template) instead. :-)

**Comment by ludwigschubert** [comment]
I'll close here, but feel free to reopen if you have specific questions or would rather not work on template directly!
